version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    # can be deleted, is only for service healthy condition in backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://user:password@database:5432/database
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    command: ["sh", "-c", "npx prisma migrate deploy && npm run db:seed && npm start"]
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/usr/src/app
